### ISSUE TITLE
奔溃问题

### ISSUE THREAD

**Issue by chengxinping** [shilec/Transer#11]
![Uploading %4OO[IM0(DMMG$BP74IAM`8.png…]()

 java.lang.NullPointerException: Entity may not be null
        at org.greenrobot.greendao.AbstractDao.getKeyVerified(AbstractDao.java:926)
        at org.greenrobot.greendao.AbstractDao.delete(AbstractDao.java:625)
        at com.scott.transer.manager.TaskDbProcessor.deleteTask(TaskDbProcessor.java:50)
        at com.scott.transer.manager.TaskProcessorProxy.deleteTask(TaskProcessorProxy.java:52)
        at com.scott.transer.manager.interceptor.DispatchCmdInterceptor.dispatch(DispatchCmdInterceptor.java:38)
        at com.scott.transer.manager.interceptor.DispatchCmdInterceptor.intercept(DispatchCmdInterceptor.java:26)
        at com.scott.transer.manager.interceptor.ChainImpl.process(ChainImpl.java:30)
        at com.scott.transer.manager.interceptor.ReNameDownloadFileInterceptor.intercept(ReNameDownloadFileInterceptor.java:37)
        at com.scott.transer.manager.interceptor.ChainImpl.process(ChainImpl.java:30)
        at com.scott.transer.manager.interceptor.CheckParamInterceptor.intercept(CheckParamInterceptor.java:24)
        at com.scott.transer.manager.interceptor.ChainImpl.process(ChainImpl.java:30)
        at com.scott.transer.manager.TaskManager.interceptCmd(TaskManager.java:65)
        at com.scott.transer.manager.TaskManager.access$000(TaskManager.java:39)
        at com.scott.transer.manager.TaskManager$1.run(TaskManager.java:92)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)

集成这个项目后 greenDao 经常奔溃 导致app闪退 请问这个问题如何解决

**Comment by shilec** [comment]
请检查删除任务时，TaskCmd 中的 task 是否为空
