### ISSUE TITLE
使用任务管理下载时taskID崩溃问题

### ISSUE THREAD

**Issue by chengxinping** [shilec/Transer#9]
您好，我通过使用任务管理器方式下载文件时，将taskID设置为文件的md5，但是下载一直报错

 android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: TASK.TASK_ID (code 1555)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:799)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
        at org.greenrobot.greendao.AbstractDao.insertInsideTx(AbstractDao.java:368)
        at org.greenrobot.greendao.AbstractDao.executeInsert(AbstractDao.java:351)
        at org.greenrobot.greendao.AbstractDao.insert(AbstractDao.java:319)
        at com.scott.transer.manager.TaskDbProcessor.addTask(TaskDbProcessor.java:36)
        at com.scott.transer.manager.TaskProcessorProxy.addTask(TaskProcessorProxy.java:36)
        at com.scott.transer.manager.interceptor.DispatchCmdInterceptor.dispatch(DispatchCmdInterceptor.java:35)
        at com.scott.transer.manager.interceptor.DispatchCmdInterceptor.intercept(DispatchCmdInterceptor.java:26)
        at com.scott.transer.manager.interceptor.ChainImpl.process(ChainImpl.java:30)
        at com.scott.transer.manager.interceptor.ReNameDownloadFileInterceptor.intercept(ReNameDownloadFileInterceptor.java:41)
        at com.scott.transer.manager.interceptor.ChainImpl.process(ChainImpl.java:30)
        at com.scott.transer.manager.interceptor.CheckParamInterceptor.intercept(CheckParamInterceptor.java:24)
        at com.scott.transer.manager.interceptor.ChainImpl.process(ChainImpl.java:30)
        at com.scott.transer.manager.TaskManager.interceptCmd(TaskManager.java:65)
        at com.scott.transer.manager.TaskManager.access$000(TaskManager.java:39)
        at com.scott.transer.manager.TaskManager$1.run(TaskManager.java:92)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)

请问这是什么原因

**Comment by chengxinping** [comment]
按道理来说 md5应该是唯一的啊 为什么会报重复
